/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as LabRouteImport } from './routes/lab'
import { Route as JunkyardRouteImport } from './routes/junkyard'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as LabSlugRouteImport } from './routes/lab.$slug'
import { Route as JunkyardSlugRouteImport } from './routes/junkyard.$slug'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const JunkyardRoute = JunkyardRouteImport.update({
  id: '/junkyard',
  path: '/junkyard',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSlugRoute = LabSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LabRoute,
} as any)
const JunkyardSlugRoute = JunkyardSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JunkyardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journey': typeof JourneyRoute
  '/junkyard': typeof JunkyardRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/writing': typeof WritingRouteWithChildren
  '/junkyard/$slug': typeof JunkyardSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journey': typeof JourneyRoute
  '/junkyard': typeof JunkyardRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/writing': typeof WritingRouteWithChildren
  '/junkyard/$slug': typeof JunkyardSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journey': typeof JourneyRoute
  '/junkyard': typeof JunkyardRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/writing': typeof WritingRouteWithChildren
  '/junkyard/$slug': typeof JunkyardSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/journey'
    | '/junkyard'
    | '/lab'
    | '/podcast'
    | '/writing'
    | '/junkyard/$slug'
    | '/lab/$slug'
    | '/projects/$slug'
    | '/writing/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/journey'
    | '/junkyard'
    | '/lab'
    | '/podcast'
    | '/writing'
    | '/junkyard/$slug'
    | '/lab/$slug'
    | '/projects/$slug'
    | '/writing/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/journey'
    | '/junkyard'
    | '/lab'
    | '/podcast'
    | '/writing'
    | '/junkyard/$slug'
    | '/lab/$slug'
    | '/projects/$slug'
    | '/writing/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JourneyRoute: typeof JourneyRoute
  JunkyardRoute: typeof JunkyardRouteWithChildren
  LabRoute: typeof LabRouteWithChildren
  PodcastRoute: typeof PodcastRoute
  WritingRoute: typeof WritingRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junkyard': {
      id: '/junkyard'
      path: '/junkyard'
      fullPath: '/junkyard'
      preLoaderRoute: typeof JunkyardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof WritingRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$slug': {
      id: '/lab/$slug'
      path: '/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof LabSlugRouteImport
      parentRoute: typeof LabRoute
    }
    '/junkyard/$slug': {
      id: '/junkyard/$slug'
      path: '/$slug'
      fullPath: '/junkyard/$slug'
      preLoaderRoute: typeof JunkyardSlugRouteImport
      parentRoute: typeof JunkyardRoute
    }
  }
}

interface JunkyardRouteChildren {
  JunkyardSlugRoute: typeof JunkyardSlugRoute
}

const JunkyardRouteChildren: JunkyardRouteChildren = {
  JunkyardSlugRoute: JunkyardSlugRoute,
}

const JunkyardRouteWithChildren = JunkyardRoute._addFileChildren(
  JunkyardRouteChildren,
)

interface LabRouteChildren {
  LabSlugRoute: typeof LabSlugRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabSlugRoute: LabSlugRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface WritingRouteChildren {
  WritingSlugRoute: typeof WritingSlugRoute
}

const WritingRouteChildren: WritingRouteChildren = {
  WritingSlugRoute: WritingSlugRoute,
}

const WritingRouteWithChildren =
  WritingRoute._addFileChildren(WritingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JourneyRoute: JourneyRoute,
  JunkyardRoute: JunkyardRouteWithChildren,
  LabRoute: LabRouteWithChildren,
  PodcastRoute: PodcastRoute,
  WritingRoute: WritingRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
